name: gwas-lecture
channels:
  - defaults
  - conda-forge/label/cf201901
dependencies:
  - python=3
  - limix=1.0.18
  - jupyter
  - matplotlib=2.2.3
  - r=3.6
  - r-irkernel
  - pytables
  - nose
  - r-ggplot2
  - r-lme4
